# .github/workflows/main.yml

name: Fetch PoE 1 Economy Data Hourly

on:
  workflow_dispatch: # Allows you to run the job manually
  schedule:
    # Runs at the top of every hour (minute 0).
    - cron: "0/20 * * * *"

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    
    # Grant permissions for the job to write to the repository
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Fetch Data Script
        run: python fetch_data.py

      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add poe1_economy.db  # Make sure this matches your DB_FILE name
          git diff --staged --quiet || git commit -m "Update PoE 1 economy data"
          git push
